function [M_ILDH,M_ILVH,M_ILPL,M_DHVH,M_DHPL,M_VHPL, F_ILDH,F_ILVH,F_ILPL,F_DHVH,F_DHPL,F_VHPL,...
    F_ILDH_D,F_ILVH_D,F_ILPL_D,F_DHVH_D,F_DHPL_D,F_VHPL_D,F_ILDH_P,F_ILVH_P,F_ILPL_P,F_DHVH_P,F_DHPL_P,F_VHPL_P,...
    F_ILDH_E,F_ILVH_E,F_ILPL_E,F_DHVH_E,F_DHPL_E,F_VHPL_E,F_ILDH_M,F_ILVH_M,F_ILPL_M,F_DHVH_M,F_DHPL_M,F_VHPL_M] ...
    = Format4Bootstrap_thetaphaselagdH(subjs,root_drIn,ILDH,ILVH,ILPL,DHVH,DHPL,VHPL)
%Format4Bootstrap_thetaphaselagdH
% [M_ILDH,M_ILVH,M_ILPL,M_DHVH,M_DHPL,M_VHPL, F_ILDH,F_ILVH,F_ILPL,F_DHVH,F_DHPL,F_VHPL,...
%     F_ILDH_D,F_ILVH_D,F_ILPL_D,F_DHVH_D,F_DHPL_D,F_VHPL_D,F_ILDH_P,F_ILVH_P,F_ILPL_P,F_DHVH_P,F_DHPL_P,F_VHPL_P,...
%     F_ILDH_E,F_ILVH_E,F_ILPL_E,F_DHVH_E,F_DHPL_E,F_VHPL_E,F_ILDH_M,F_ILVH_M,F_ILPL_M,F_DHVH_M,F_DHPL_M,F_VHPL_M] ...
%     = Format4Bootstrap_thetaphaselagdH(subjs,root_drIn,ILDH,ILVH,ILPL,DHVH,DHPL,VHPL)
% 
%  Familiar arena (BL) data, only epochs when dHPC power is greater than its mean power for that recording
%   MALE DATA:
%       M{1,1} = data(ntrials,ntimestamps)  Male subject 1
%       M{2,1} = data(27,XXXX)  Male subject 2 (example: 27 trials, Coherence data with length(f)=XXXX)
% 
%   FEMALE DATA:    
%       Same as above, but 2nd dimension of cell array indexes estrous stage:
%         F{:,1}=Diestrus (D)
%         F{:,2}=Proestrus (P)
%         F{:,3}=Estrus (E)
%         F{:,4}=Metestrus (M)  **Included for MvF comparisons, Ignored for female hormone comparisons**
% 
%   INPUT DATA:
%       Generated by ThetaPhaseLagdH.m
% 
%       Data format:
%         Row1: inter-regional phase difference time series
%         Row2: histogram of ^
%         Row3: Phase where peak is located
%         Row4: Width at half-max of peak

% KJS init: 2020-01-15
% KJS edit 2020-02-12: fixed a typo
% KJS edit 2020-02-13: format as function
% KJS edit 2020-03-02: format for compatiblity with get_bootstrapped_sample.m

%% Setup

% Subject ID listing A*=male  E*=female
Msubjs = subjs(contains(subjs,'A')); %male subject IDs
Fsubjs = subjs(contains(subjs,'E')); %female subject IDs

%% Males
% Preallocate output space
M_ILDH = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % mPFCil-dHPC
M_ILVH = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % mPFCil-vHPC
M_ILPL = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % mPFCil-mPFCpl
M_DHVH = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % dHPC-vHPC
M_DHPL = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % dHPC-mPFCpl
M_VHPL = cell(length(Msubjs), max(cellfun('prodofsize',ILDH(1:4)))/length(Msubjs));  % vHPC-mPFCpl
    
% Width at half-max peak
for si = 1:length(Msubjs) %loop thru male subjects
    for ri = 1:size(ILDH{1,si},2) %loop trials
        M_ILDH{si,ri} = ILDH{1,si}{4,ri};
        M_ILVH{si,ri} = ILVH{1,si}{4,ri};
        M_ILPL{si,ri} = ILPL{1,si}{4,ri};
        M_DHVH{si,ri} = DHVH{1,si}{4,ri};
        M_DHPL{si,ri} = DHPL{1,si}{4,ri};
        M_VHPL{si,ri} = VHPL{1,si}{4,ri};
    end
end
clear si ri
    
    
    
%% Females: All hormone states combined
maxT = 28; %maximum number of trials for any given female subject
% Preallocate output space
F_ILDH = cell(length(Fsubjs),maxT);
F_ILVH = cell(length(Fsubjs),maxT);
F_ILPL = cell(length(Fsubjs),maxT);
F_DHVH = cell(length(Fsubjs),maxT);
F_DHPL = cell(length(Fsubjs),maxT);
F_VHPL = cell(length(Fsubjs),maxT);
clear maxT

for fi = 1:length(Fsubjs) %loop female subjects
    si = fi+length(Msubjs); %subject index in full dataset
    for ri = 1:size(ILDH{1,si},2) %loop trials 
        F_ILDH{fi,ri} = ILDH{1,si}{4,ri};
        F_ILVH{fi,ri} = ILVH{1,si}{4,ri};
        F_ILPL{fi,ri} = ILPL{1,si}{4,ri};
        F_DHVH{fi,ri} = DHVH{1,si}{4,ri};
        F_DHPL{fi,ri} = DHPL{1,si}{4,ri};
        F_VHPL{fi,ri} = VHPL{1,si}{4,ri};
    end
end
clear si ri fi


%% Females: Hormone stages separated   
maxD = 14;
maxP = 9;
maxE = 9;
maxM = 3;
% Preallocate space: Diestrus
    F_ILDH_D = cell(length(Fsubjs),maxD);
    F_ILVH_D = cell(length(Fsubjs),maxD);
    F_ILPL_D = cell(length(Fsubjs),maxD);
    F_DHVH_D = cell(length(Fsubjs),maxD);
    F_DHPL_D = cell(length(Fsubjs),maxD);
    F_VHPL_D = cell(length(Fsubjs),maxD);
    clear maxD
% Preallocate space: Proestrus
    F_ILDH_P = cell(length(Fsubjs),maxP);
    F_ILVH_P = cell(length(Fsubjs),maxP);
    F_ILPL_P = cell(length(Fsubjs),maxP);
    F_DHVH_P = cell(length(Fsubjs),maxP);
    F_DHPL_P = cell(length(Fsubjs),maxP);
    F_VHPL_P = cell(length(Fsubjs),maxP);
    clear maxP
% Preallocate space: Estrus
    F_ILDH_E = cell(length(Fsubjs),maxE);
    F_ILVH_E = cell(length(Fsubjs),maxE);
    F_ILPL_E = cell(length(Fsubjs),maxE);
    F_DHVH_E = cell(length(Fsubjs),maxE);
    F_DHPL_E = cell(length(Fsubjs),maxE);
    F_VHPL_E = cell(length(Fsubjs),maxE);
    clear maxE
% Preallocate space: Metestrus
    F_ILDH_M = cell(length(Fsubjs),maxM);
    F_ILVH_M = cell(length(Fsubjs),maxM);
    F_ILPL_M = cell(length(Fsubjs),maxM);
    F_DHVH_M = cell(length(Fsubjs),maxM);
    F_DHPL_M = cell(length(Fsubjs),maxM);
    F_VHPL_M = cell(length(Fsubjs),maxM);
    clear maxM

    
for si = 1:length(Fsubjs)
    sidx = si+length(Msubjs); %index for female subject within combined dataset
    subjID = subjs{sidx};

%    Load index for hormone states across recordings
%        idx format:
%         (:,1) = Diestrus
%         (:,2) = Proestrus
%         (:,3) = Estrus
%         (:,4) = Metestrus
    fnn = [subjID '_ThetaFiltfilt.mat']; % file name to load
    load([root_drIn 'BL' filesep subjID filesep fnn],'idx')
    clear fnn
        if size(idx,1) < size(idx,2)
            idx = idx';
        end
    
    for ti = 1:4 %loop thru hormone states: column 1=Diestrus, 2=Proestrus, 3=Estrus, 4=Metestrus
        hidx = find(idx(:,ti)==1); %index of trials in this state
        for ri = 1:length(hidx) %loop trials in this hormone state
            switch ti
                case 1 %Diestrus
                    F_ILDH_D{si,ri} = ILDH{1,sidx}{4,hidx(ri)};
                    F_ILVH_D{si,ri} = ILVH{1,sidx}{4,hidx(ri)};
                    F_ILPL_D{si,ri} = ILPL{1,sidx}{4,hidx(ri)};
                    F_DHVH_D{si,ri} = DHVH{1,sidx}{4,hidx(ri)};
                    F_DHPL_D{si,ri} = DHPL{1,sidx}{4,hidx(ri)};
                    F_VHPL_D{si,ri} = VHPL{1,sidx}{4,hidx(ri)};
                case 2 %Proestrus
                    F_ILDH_P{si,ri} = ILDH{1,sidx}{4,hidx(ri)};
                    F_ILVH_P{si,ri} = ILVH{1,sidx}{4,hidx(ri)};
                    F_ILPL_P{si,ri} = ILPL{1,sidx}{4,hidx(ri)};
                    F_DHVH_P{si,ri} = DHVH{1,sidx}{4,hidx(ri)};
                    F_DHPL_P{si,ri} = DHPL{1,sidx}{4,hidx(ri)};
                    F_VHPL_P{si,ri} = VHPL{1,sidx}{4,hidx(ri)};
                case 3
                    F_ILDH_E{si,ri} = ILDH{1,sidx}{4,hidx(ri)};
                    F_ILVH_E{si,ri} = ILVH{1,sidx}{4,hidx(ri)};
                    F_ILPL_E{si,ri} = ILPL{1,sidx}{4,hidx(ri)};
                    F_DHVH_E{si,ri} = DHVH{1,sidx}{4,hidx(ri)};
                    F_DHPL_E{si,ri} = DHPL{1,sidx}{4,hidx(ri)};
                    F_VHPL_E{si,ri} = VHPL{1,sidx}{4,hidx(ri)};
                case 4
                    F_ILDH_M{si,ri} = ILDH{1,sidx}{4,hidx(ri)};
                    F_ILVH_M{si,ri} = ILVH{1,sidx}{4,hidx(ri)};
                    F_ILPL_M{si,ri} = ILPL{1,sidx}{4,hidx(ri)};
                    F_DHVH_M{si,ri} = DHVH{1,sidx}{4,hidx(ri)};
                    F_DHPL_M{si,ri} = DHPL{1,sidx}{4,hidx(ri)};
                    F_VHPL_M{si,ri} = VHPL{1,sidx}{4,hidx(ri)};
            end %switch
            clear ri
        end %trials
        clear hidx
    end %hormones
    clear idx ti sidx subjID
end %Fsubjs
clear si 

end %function



%% script not used below. IGNORE
%     Loop thru trials
%     for ti = 1:size(idx,1)  %#ok<*NODEF>
%         hidx = find(idx(ti,:)==1); %#ok<*IDISVAR> %index for which hormone state to output   
%         [F_ILDH{si,hidx}(ti,:)] = ILDH{1,sidx}{4,ti};
%         [F_ILVH{si,hidx}(ti,:)] = ILVH{1,sidx}{4,ti};
%         [F_ILPL{si,hidx}(ti,:)] = ILPL{1,sidx}{4,ti};
%         [F_DHVH{si,hidx}(ti,:)] = DHVH{1,sidx}{4,ti};
%         [F_DHPL{si,hidx}(ti,:)] = DHPL{1,sidx}{4,ti};
%         [F_VHPL{si,hidx}(ti,:)] = VHPL{1,sidx}{4,ti};
%         clear hidx       
%     end 
%     clear ti
% 
% %     Remove empty cells
%     for i = 1:4 %loop thru columns/hormone states
%         id = find(F_ILDH{si,i}(:,1)==0); %index of empty rows to remove
%         F_ILDH{si,i}(id,:) = [];
%         F_ILVH{si,i}(id,:) = [];
%         F_ILPL{si,i}(id,:) = [];
%         F_DHVH{si,i}(id,:) = [];
%         F_DHPL{si,i}(id,:) = [];
%         F_VHPL{si,i}(id,:) = [];
%         clear id
%     end
%     clear i sidx subjID idx
% end %Fsubjs
% clear si ILDH ILPL ILVH DHPL DHVH VHPL 