%% Z-score Bootstrap_Rsq
% 
% Z-scores Theta, Gamma, and Delta power correlation values (R^2 ), all
% movement velocities
% 
% Uses data generated by: BandPowerCrossCorr_AllVelocityBL.m --reshape---> *Format4Bootstrap_Rsq.m *
% 
% example:
%       drIn = 'K:\Personal Folders\Kristin Schoepfer\Neuralynx\DATA\REVAMPED\dat\ReducedEEG\BL\';
%       load([drIn 'ThetaRsq-BL_boot.mat'])
% 
% KJS init: 2020-01-31, edit/complete 2020-02-03
% KJS edit 2020-02-14: modified as fxn, save outside the script
% 
function [M_ILDH_z, M_ILVH_z, M_ILPL_z, M_DHVH_z, M_DHPL_z, M_VHPL_z, ...
    F_ILDH_z, F_ILVH_z, F_ILPL_z, F_DHVH_z, F_DHPL_z, F_VHPL_z,Z_all] = ...
    ZscoreRsq_boot(M_ILDH, M_ILVH, M_ILPL, M_DHVH, M_DHPL, M_VHPL, ...
    F_ILDH, F_ILVH, F_ILPL, F_DHVH, F_DHPL, F_VHPL)
%% Put all data together (all connections)
Malldat = cell2mat([M_ILDH M_ILVH M_ILPL M_DHVH M_DHPL M_VHPL]); %males
FDalldat = cell2mat([F_ILDH(:,1) F_ILVH(:,1) F_ILPL(:,1) F_DHVH(:,1) F_DHPL(:,1) F_VHPL(:,1)]); %females - diestrus
FPalldat = cell2mat([F_ILDH(:,2) F_ILVH(:,2) F_ILPL(:,2) F_DHVH(:,2) F_DHPL(:,2) F_VHPL(:,2)]); %females - proestrus
FEalldat = cell2mat([F_ILDH(:,3) F_ILVH(:,3) F_ILPL(:,3) F_DHVH(:,3) F_DHPL(:,3) F_VHPL(:,3)]); %females - estrus
FMalldat = cell2mat([F_ILDH(:,4) F_ILVH(:,4) F_ILPL(:,4) F_DHVH(:,4) F_DHPL(:,4) F_VHPL(:,4)]); %females - metestrus
Falldat = [FDalldat; FPalldat; FEalldat; FMalldat]; %females - all stages
alldat = [Malldat; Falldat]; %everyone

%% Z-score everything together - within-connection
% [Z_all,mu_all,sigma_all] = zscore(alldat,0,1);
[Z_all] = zscore(alldat,0,1);
% [Z_M] = zscore(Malldat,0,1);
% [Z_F] = zscore(Falldat,0,1);
clear alldat
    
%% Output Z-scores back into boostrap shape
mz = Z_all(1:size(Malldat,1),:); %males - all connections
fz = Z_all(size(Malldat,1)+1:end,:); %females - all connections

%% Males
M_ILDH_z = mat2cell(mz(:,1),[length(M_ILDH{1}) length(M_ILDH{2}) length(M_ILDH{3}) length(M_ILDH{4})]);
M_ILVH_z = mat2cell(mz(:,2),[length(M_ILVH{1}) length(M_ILVH{2}) length(M_ILVH{3}) length(M_ILVH{4})]);
M_ILPL_z = mat2cell(mz(:,3),[length(M_ILPL{1}) length(M_ILPL{2}) length(M_ILPL{3}) length(M_ILPL{4})]);
M_DHVH_z = mat2cell(mz(:,4),[length(M_DHVH{1}) length(M_DHVH{2}) length(M_DHVH{3}) length(M_DHVH{4})]);
M_DHPL_z = mat2cell(mz(:,5),[length(M_DHPL{1}) length(M_DHPL{2}) length(M_DHPL{3}) length(M_DHPL{4})]);
M_VHPL_z = mat2cell(mz(:,6),[length(M_VHPL{1}) length(M_VHPL{2}) length(M_VHPL{3}) length(M_VHPL{4})]);
clear mz M_ILDH M_ILVH M_ILPL M_DHVH M_DHPL M_VHPL Malldat

%% Females
F_ILDH_z = mat2cell(fz(:,1),[length(F_ILDH{1,1}) length(F_ILDH{2,1}) length(F_ILDH{3,1}) length(F_ILDH{4,1}) length(F_ILDH{5,1}), ...
                            length(F_ILDH{1,2}) length(F_ILDH{2,2}) length(F_ILDH{3,2}) length(F_ILDH{4,2}) length(F_ILDH{5,2}),...
                            length(F_ILDH{1,3}) length(F_ILDH{2,3}) length(F_ILDH{3,3}) length(F_ILDH{4,3}) length(F_ILDH{5,3}),...
                            length(F_ILDH{1,4}) length(F_ILDH{2,4}) length(F_ILDH{3,4}) length(F_ILDH{4,4}) length(F_ILDH{5,4})]);
F_ILVH_z = mat2cell(fz(:,2),[length(F_ILVH{1,1}) length(F_ILVH{2,1}) length(F_ILVH{3,1}) length(F_ILVH{4,1}) length(F_ILVH{5,1}), ...
                            length(F_ILVH{1,2}) length(F_ILVH{2,2}) length(F_ILVH{3,2}) length(F_ILVH{4,2}) length(F_ILVH{5,2}),...
                            length(F_ILVH{1,3}) length(F_ILVH{2,3}) length(F_ILVH{3,3}) length(F_ILVH{4,3}) length(F_ILVH{5,3}),...
                            length(F_ILVH{1,4}) length(F_ILVH{2,4}) length(F_ILVH{3,4}) length(F_ILVH{4,4}) length(F_ILVH{5,4})]);
F_ILPL_z = mat2cell(fz(:,3),[length(F_ILPL{1,1}) length(F_ILPL{2,1}) length(F_ILPL{3,1}) length(F_ILPL{4,1}) length(F_ILPL{5,1}), ...
                            length(F_ILPL{1,2}) length(F_ILPL{2,2}) length(F_ILPL{3,2}) length(F_ILPL{4,2}) length(F_ILPL{5,2}),...
                            length(F_ILPL{1,3}) length(F_ILPL{2,3}) length(F_ILPL{3,3}) length(F_ILPL{4,3}) length(F_ILPL{5,3}),...
                            length(F_ILPL{1,4}) length(F_ILPL{2,4}) length(F_ILPL{3,4}) length(F_ILPL{4,4}) length(F_ILPL{5,4})]);
F_DHVH_z = mat2cell(fz(:,4),[length(F_DHVH{1,1}) length(F_DHVH{2,1}) length(F_DHVH{3,1}) length(F_DHVH{4,1}) length(F_DHVH{5,1}), ...
                            length(F_DHVH{1,2}) length(F_DHVH{2,2}) length(F_DHVH{3,2}) length(F_DHVH{4,2}) length(F_DHVH{5,2}),...
                            length(F_DHVH{1,3}) length(F_DHVH{2,3}) length(F_DHVH{3,3}) length(F_DHVH{4,3}) length(F_DHVH{5,3}),...
                            length(F_DHVH{1,4}) length(F_DHVH{2,4}) length(F_DHVH{3,4}) length(F_DHVH{4,4}) length(F_DHVH{5,4})]);
F_DHPL_z = mat2cell(fz(:,5),[length(F_DHPL{1,1}) length(F_DHPL{2,1}) length(F_DHPL{3,1}) length(F_DHPL{4,1}) length(F_DHPL{5,1}), ...
                            length(F_DHPL{1,2}) length(F_DHPL{2,2}) length(F_DHPL{3,2}) length(F_DHPL{4,2}) length(F_DHPL{5,2}),...
                            length(F_DHPL{1,3}) length(F_DHPL{2,3}) length(F_DHPL{3,3}) length(F_DHPL{4,3}) length(F_DHPL{5,3}),...
                            length(F_DHPL{1,4}) length(F_DHPL{2,4}) length(F_DHPL{3,4}) length(F_DHPL{4,4}) length(F_DHPL{5,4})]);
F_VHPL_z = mat2cell(fz(:,6),[length(F_VHPL{1,1}) length(F_VHPL{2,1}) length(F_VHPL{3,1}) length(F_VHPL{4,1}) length(F_VHPL{5,1}), ...
                            length(F_VHPL{1,2}) length(F_VHPL{2,2}) length(F_VHPL{3,2}) length(F_VHPL{4,2}) length(F_VHPL{5,2}),...
                            length(F_VHPL{1,3}) length(F_VHPL{2,3}) length(F_VHPL{3,3}) length(F_VHPL{4,3}) length(F_VHPL{5,3}),...
                            length(F_VHPL{1,4}) length(F_VHPL{2,4}) length(F_VHPL{3,4}) length(F_VHPL{4,4}) length(F_VHPL{5,4})]);
% Reshape 
F_ILDH_z = reshape(F_ILDH_z,size(F_ILDH));
F_ILVH_z = reshape(F_ILVH_z,size(F_ILVH));
F_ILPL_z = reshape(F_ILPL_z,size(F_ILPL));
F_DHVH_z = reshape(F_DHVH_z,size(F_DHVH));
F_DHPL_z = reshape(F_DHPL_z,size(F_DHPL));
F_VHPL_z = reshape(F_VHPL_z,size(F_VHPL));

clear F_ILDH F_ILVH F_ILPL F_DHVH F_DHPL F_VHPL fz Falldat FDalldat FEalldat FMalldat FPalldat

end %function
