function [Mx_theta_boot,Fx_theta_boot,Mx_gamma_boot,Fx_gamma_boot,Mx_delta_boot,Fx_delta_boot,MF_theta_p_test, MF_gamma_p_test, MF_delta_p_test,MF_pjmtheta,MF_pjmgamma,MF_pjmdelta] = BootStat_MvF(Mx_theta,Mx_gamma,Mx_delta,Fx_theta,Fx_gamma,Fx_delta)
%BootStat_MvF
% [Mx_theta_boot,Fx_theta_boot,Mx_gamma_boot,Fx_gamma_boot,Mx_delta_boot,Fx_delta_boot,MF_theta_p_test, MF_gamma_p_test, MF_delta_p_test,MF_pjmtheta,MF_pjmgamma,MF_pjmdelta] = BootStat_MvF(Mx_theta,Mx_gamma,Mx_delta,Fx_theta,Fx_gamma,Fx_delta)
% 
% Calculates bootstrap resampling of unidimensional data in a
% single-variable sex differences comparison. This script is oriented for
% analyzing single-region band power for theta, gamma, and delta bands.
%   Data generated by: 'FreqBandPow-BL-5to15_boot.mat' (generated by 
%   Format4Bootstrap_BandPower2.m, called within Thesis6_*_5to15.m)
% 
% Frequency band definitions:
%   Theta: 4-12 Hz
%   Gamma: 30-80 Hz
%   Delta: 1-4 Hz
% 
% OUTPUTS:
%   - Mx_*_boot     Bootstrapped samples 
%   - MF_*_p_test   Probability estimate of Female sample (variable2) being
%                   greater than Male sample (variable1).
%   - MF_pjm*       Frequency band joint-probability matrix (size: 100x100).
% 
%   CALLS FUNCTIONS:
%       - get_bootstrapped_sample.m
%       - get_direct_prob.m
% 
% KJS init: 2020-03-03
% KJS edit: 2020-03-05
% KJS edit: 2020-03-13 Added *_boot outputs

%% setup
nboot = 10^4;
f_n=1;

%% Get bootstrapped samples: Male 
Mx_theta_boot = get_bootstrapped_sample(Mx_theta, nboot, f_n); 
Mx_gamma_boot = get_bootstrapped_sample(Mx_gamma, nboot, f_n); 
Mx_delta_boot = get_bootstrapped_sample(Mx_delta, nboot, f_n); 

%% Get bootstrapped samples: Female (all trials) Band power  
Fx_theta_boot = get_bootstrapped_sample(Fx_theta, nboot, f_n); 
Fx_gamma_boot = get_bootstrapped_sample(Fx_gamma, nboot, f_n); 
Fx_delta_boot = get_bootstrapped_sample(Fx_delta, nboot, f_n); 

%% Ptest: Males vs Females 

[MF_theta_p_test,MF_pjmtheta] = get_direct_prob(Mx_theta_boot, Fx_theta_boot);
[MF_gamma_p_test,MF_pjmgamma] = get_direct_prob(Mx_gamma_boot, Fx_gamma_boot);
[MF_delta_p_test,MF_pjmdelta] = get_direct_prob(Mx_delta_boot, Fx_delta_boot);

end



%% unused code below from previous version
% % dHPC
% [MF_DH_theta_p_test,MF_DHth_pjm] = get_direct_prob(M_DH_theta_boot, F_DH_theta_boot);
% MF_DH_gamma_p_test = get_direct_prob(M_DH_gamma_boot, F_DH_gamma_boot);
% MF_DH_delta_p_test = get_direct_prob(M_DH_delta_boot, F_DH_delta_boot);
% 
% % vHPC
% [MF_VH_theta_p_test,MF_VHth_pjm] = get_direct_prob(M_VH_theta_boot, F_VH_theta_boot);
% MF_VH_gamma_p_test = get_direct_prob(M_VH_gamma_boot, F_VH_gamma_boot);
% MF_VH_delta_p_test = get_direct_prob(M_VH_delta_boot, F_VH_delta_boot);
% 
% % mPFC-PL
% [MF_PL_theta_p_test,MF_PLth_pjm] = get_direct_prob(M_PL_theta_boot, F_PL_theta_boot);
% MF_PL_gamma_p_test = get_direct_prob(M_PL_gamma_boot, F_PL_gamma_boot);
% MF_PL_delta_p_test = get_direct_prob(M_PL_delta_boot, F_PL_delta_boot);
% 
% % Plot theta band joint-probability matrices
% x = linspace(0,100); %unity line
% h = figure('units','normalized','outerposition',[0 0 1 1]);
% ax1 = subplot(221); %IL
%     imagesc(MF_pjm); hold on; plot(x,x,'k','linew',2);
%     axis xy square; xlabel('Male mPFC-IL'); ylabel('Female mPFC-IL')
%     set(gca,'fontsize',14)
%     colormap(ax1,jet)
% ax2 = subplot(222); %DH
%     imagesc(MF_DHth_pjm); hold on; plot(x,x,'k','linew',2);
%     axis xy square; xlabel('Male dHPC'); ylabel('Female dHPC')
%     set(gca,'fontsize',14,'TitleFontSizeMultiplier',1.5)
%     colormap(ax2,jet)
% ax3 = subplot(223); %VH
%     imagesc(MF_VHth_pjm); hold on; plot(x,x,'k','linew',2);
%     axis xy square; xlabel('Male vHPC'); ylabel('Female vHPC')
%     set(gca,'fontsize',14)
%     colormap(ax3,jet)
% ax4 = subplot(224); %PL
%     imagesc(MF_PLth_pjm); hold on; plot(x,x,'k','linew',2);
%     axis xy square; xlabel('Male mPFC-PL'); ylabel('Female mPFC-PL')
%     set(gca,'fontsize',14)
%     colormap(ax4,jet)
% % Create textbox for figure title
% annotation(h,'textbox',[0.308740324594257 0.944323314529585 0.427370786516854 0.0508054522924403],...
%     'String','Theta band power: Joint-Probability matrices',...
%     'HorizontalAlignment','center','FontWeight','bold','FontSize',21,...
%     'FitBoxToText','off','EdgeColor',[0.941176470588235 0.941176470588235 0.941176470588235]);
%     

% Male vs Female: Theta/Gamma/Delta bands
%     MF_theta_p_test = [MF_DH_theta_p_test, MF_VH_theta_p_test, MF_PL_theta_p_test, MF_theta_p_test]';
%     MF_gamma_p_test = [MF_DH_gamma_p_test, MF_VH_gamma_p_test, MF_PL_gamma_p_test, MF_gamma_p_test]';
%     MF_delta_p_test = [MF_DH_delta_p_test, MF_VH_delta_p_test, MF_PL_delta_p_test, MF_delta_p_test]';
%     T_MF = table(brain_area, MF_theta_p_test, MF_gamma_p_test, MF_delta_p_test);



