%% Format4Bootstrap_mscohereHormones
% [F_ILDH,F_ILVH,F_ILPL,F_DHVH,F_DHPL,F_VHPL] = Format4Bootstrap_mscohereHormones(Fsubjs,F_IL,F_DH,F_VH,F_PL)
% 
%  Uses built-in function from Signal Processing Toolbox: mscohere
%   ** Signal Processing Toolbox must be installed **
% 
% Generates magnitude-squared coherence for female subjects, using 
% concatenated data from all familiar (BL) arena recordings, epochs of 
% locomotor movement between 5-15 cm/s. 
% Female data is separated by hormone state, within-subject.
% 
%   2nd dimension of each cell array indexes estrous stage:
%     F_*{:,1}=Diestrus (D)
%     F_*{:,2}=Proestrus (P)
%     F_*{:,3}=Estrus (E)
%     F_*{:,4}=Metestrus (M)  **Included for MvF comparisons, Ignored for female hormone comparisons**
% 
%   Fetches data generated by:
%       Format4Bootstrap_LFP.m            'LFP-BL-5to15_boot.mat'
% 
%   Called by:
%       Thesis6_Format4Bootstrap_5to15.m
% 
% Lengthy runtime (all trials concat.), ~5-10min/subj
% 
% KJS init: 2020-01-14
% KJS edit 2020-02-27: Format as function

function [F_ILDH,F_ILVH,F_ILPL,F_DHVH,F_DHPL,F_VHPL] ...
    = Format4Bootstrap_mscohereHormones(Fsubjs,F_IL,F_DH,F_VH,F_PL)
%% Setup

% mscohere parameters
Fs = 2000; %sampling frequency (Hz)
nfft=Fs*2;
window = hann(nfft);
noverlap = nfft/2;
F = 0.5:0.5:100; %frequency vector [0.5 - 100] Hz

% Preallocate output space
F_ILDH = cell(length(Fsubjs),4);  % mPFCil-dHPC
F_ILVH = cell(length(Fsubjs),4);  % mPFCil-vHPC
F_ILPL = cell(length(Fsubjs),4);  % mPFCil-mPFCpl
F_DHVH = cell(length(Fsubjs),4);  % dHPC-vHPC
F_DHPL = cell(length(Fsubjs),4);  % dHPC-mPFCpl
F_VHPL = cell(length(Fsubjs),4);  % vHPC-mPFCpl

%% Shape data: Coherence, BL arena, 5-15 cm/s velocity
for si = 1:length(Fsubjs)
    tic;
    fprintf('Processing mscohere for %s...\n',Fsubjs{si})
     for hidx = 1:4 %loop hormone states
         switch hidx
             case 1
                 disp('Diestrus recordings')
             case 2
                 disp('Proestrus recordings')
             case 3
                 disp('Estrus recordings')
             case 4
                 disp('Metestrus recordings')
         end
        [F_ILDH{si,hidx}] = mscohere(cell2mat(F_IL{si,hidx}(:)),cell2mat(F_DH{si,hidx}(:)),window,noverlap,F,Fs);
        disp('.')
        [F_ILVH{si,hidx}] = mscohere(cell2mat(F_IL{si,hidx}(:)),cell2mat(F_VH{si,hidx}(:)),window,noverlap,F,Fs);
        disp('..')
        [F_ILPL{si,hidx}] = mscohere(cell2mat(F_IL{si,hidx}(:)),cell2mat(F_PL{si,hidx}(:)),window,noverlap,F,Fs);
        disp('...')
        [F_DHVH{si,hidx}] = mscohere(cell2mat(F_DH{si,hidx}(:)),cell2mat(F_VH{si,hidx}(:)),window,noverlap,F,Fs);
        disp('....')
        [F_DHPL{si,hidx}] = mscohere(cell2mat(F_DH{si,hidx}(:)),cell2mat(F_PL{si,hidx}(:)),window,noverlap,F,Fs);
        disp('.....')
        [F_VHPL{si,hidx}] = mscohere(cell2mat(F_VH{si,hidx}(:)),cell2mat(F_PL{si,hidx}(:)),window,noverlap,F,Fs);
    end %hormones
    toc
    clear hidx
end 
clear si subjID F_IL F_DH F_VH F_PL

end %function
  






%% extra code not used here. Ignore below.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % Loop thru trials
%     for ti = 1:size(idx,1) 
%         fprintf('Trial %i of %i\n',ti,size(medidx,2))
%         hidx = find(idx(ti,:)==1); %index for which hormone state to output   
%         tic;
%         if ti==1 %trial 1, also output 'f' (frequency vector)
%             [F_ILDH{si,hidx}(ti,:),f] = mscohere(medIL(medidx{1,ti}(:),ti),medDHIP(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         else %not trial 1
%             [F_ILDH{si,hidx}(ti,:)] = mscohere(medIL(medidx{1,ti}(:),ti),medDHIP(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         end %trial check
%         [F_ILVH{si,hidx}(ti,:)] = mscohere(medIL(medidx{1,ti}(:),ti),medVHIP(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         [F_ILPL{si,hidx}(ti,:)] = mscohere(medIL(medidx{1,ti}(:),ti),medPL(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         [F_DHVH{si,hidx}(ti,:)] = mscohere(medDHIP(medidx{1,ti}(:),ti),medVHIP(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         [F_DHPL{si,hidx}(ti,:)] = mscohere(medDHIP(medidx{1,ti}(:),ti),medPL(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         [F_VHPL{si,hidx}(ti,:)] = mscohere(medVHIP(medidx{1,ti}(:),ti),medPL(medidx{1,ti}(:),ti),window,noverlap,F,Fs);
%         toc
%         clear hidx       
%     end %trials. these loops take ~100 sec/ea
%     clear ti med* subjID

%     % Remove empty cells
%     for i = 1:4 %loop thru columns/hormone states
%         idx = find(F_ILDH{si,i}(:,1)==0); %index of empty rows to remove
%         F_ILDH{si,i}(idx,:) = [];
%         F_ILVH{si,i}(idx,:) = [];
%         F_ILPL{si,i}(idx,:) = [];
%         F_DHVH{si,i}(idx,:) = [];
%         F_DHPL{si,i}(idx,:) = [];
%         F_VHPL{si,i}(idx,:) = [];
%         clear idx
%     end
%     clear i list
% end %Fsubjs
% clear si
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%     % Load data and time indices for 5-15 cm/s movement, all trials
%     fn = [subjID '_ReducedDataPerSpeed.mat']; % file name to load
%     load([root_drIn subjID filesep fn],'medidx','medIL','medPL','medDHIP','medVHIP','*list')
%     clear fn

%     % Index trials by hormone state
%     if exist('BLlist','var')
%         list = BLlist; clear BLlist;
%     else %Rxlist
%         list = Rxlist; clear Rxlist;
%     end
%     Didx = contains(list,'_D');
%     Pidx = contains(list,'_P');
%     Eidx = contains(list,'_E');
%     if any(contains(list,'M'))
%         Midx = contains(list,'_M');
%     else
%         Midx = false(length(list),1);
%     end
%     idx = double([Didx Pidx Eidx Midx]);
%     clear Didx Pidx Eidx Midx    
% 
% for si = 1:length(Fsubjs)
%     tic;
%     fprintf('Processing mscohere for %s...\n',Fsubjs{si})
%      for hidx = 1:4 %loop hormone states
%         switch hidx
%             case 1; hs='Diestrus';
%             case 2; hs='Proestrus';
%             case 3; hs='Estrus';
%             case 4; hs='Metestrus';
%         end
%         for ri = 1:length(F_IL{si,hidx}) %loop trials
%             fprintf('%s trial %i of %i\n',hs,ri,length(F_IL{si,hidx}))
%             if si==1 && ri==1
%                 [F_ILDH{si,hidx}{ri},~,~,~,~,f] = coherencyc(F_IL{si,hidx}{ri,1}',F_DH{si,hidx}{ri,1}',params);
%             else
%                 [F_ILDH{si,hidx}{ri}] = coherencyc(F_IL{si,hidx}{ri,1}',F_DH{si,hidx}{ri,1}',params); 
%             end
%             disp('.')
%             [F_ILVH{si,hidx}{ri}] = coherencyc(F_IL{si,hidx}{ri,1}',F_VH{si,hidx}{ri,1}',params);
%             disp('..')
%             [F_ILPL{si,hidx}{ri}] = coherencyc(F_IL{si,hidx}{ri,1}',F_PL{si,hidx}{ri,1}',params);
%             disp('...')
%             [F_DHVH{si,hidx}{ri}] = coherencyc(F_DH{si,hidx}{ri,1}',F_VH{si,hidx}{ri,1}',params);
%             disp('....')
%             [F_DHPL{si,hidx}{ri}] = coherencyc(F_DH{si,hidx}{ri,1}',F_PL{si,hidx}{ri,1}',params);
%             disp('.....')
%             [F_VHPL{si,hidx}{ri}] = coherencyc(F_VH{si,hidx}{ri,1}',F_PL{si,hidx}{ri,1}',params);
%         end %trials
%         clear hs ri
%     end %hormones
%     toc
%     clear hidx
% end 
% clear si subjID F_IL F_DH F_VH F_PL

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
