%Format4Bootstrap_BandPower2
% [M_IL_theta,M_IL_gamma,M_IL_delta,M_DH_theta,M_DH_gamma,M_DH_delta,M_VH_theta,M_VH_gamma,M_VH_delta,M_PL_theta,M_PL_gamma,M_PL_delta,...
%     F_IL_theta,F_IL_gamma,F_IL_delta,F_DH_theta,F_DH_gamma,F_DH_delta,F_VH_theta,F_VH_gamma,F_VH_delta,F_PL_theta,F_PL_gamma,F_PL_delta,...
%     F_IL_D_theta,F_IL_D_gamma,F_IL_D_delta,F_DH_D_theta,F_DH_D_gamma,F_DH_D_delta,F_VH_D_theta,F_VH_D_gamma,F_VH_D_delta,F_PL_D_theta,F_PL_D_gamma,F_PL_D_delta,...
%     F_IL_P_theta,F_IL_P_gamma,F_IL_P_delta,F_DH_P_theta,F_DH_P_gamma,F_DH_P_delta,F_VH_P_theta,F_VH_P_gamma,F_VH_P_delta,F_PL_P_theta,F_PL_P_gamma,F_PL_P_delta,...
%     F_IL_E_theta,F_IL_E_gamma,F_IL_E_delta,F_DH_E_theta,F_DH_E_gamma,F_DH_E_delta,F_VH_E_theta,F_VH_E_gamma,F_VH_E_delta,F_PL_E_theta,F_PL_E_gamma,F_PL_E_delta,...
%     F_IL_M_theta,F_IL_M_gamma,F_IL_M_delta,F_DH_M_theta,F_DH_M_gamma,F_DH_M_delta,F_VH_M_theta,F_VH_M_gamma,F_VH_M_delta,F_PL_M_theta,F_PL_M_gamma,F_PL_M_delta] ...
%     = Format4Bootstrap_BandPower2(subjs,f,M_IL_Pxx,M_PL_Pxx,M_DH_Pxx,M_VH_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx)
% 
% Theta, Gamma, and Delta band powers in each brain region, per recording.
% 
% Familiar arena (BL) data, only epochs of movement between 5-15 cm/s.
% 
% Each output variable contains a subjects x ntrials cell array of
% frequency band power across trials.
% 
%   Fetches data generated by:
%       - PowSpec5to15.m: 'Pxx-BL-5to15.mat' (called within Thesis6_Format4Bootstrap_5to15.m)
%       -PowSpec5to15_Hormones.m 'PxxHormones-BL-5to15.mat' (called within " ")
% 
%   Called by:
%       Thesis6_Format4Bootstrap_5to15.m
% 
% KJS init: 2020-02-26

function [M_IL_theta,M_IL_gamma,M_IL_delta,M_DH_theta,M_DH_gamma,M_DH_delta,M_VH_theta,M_VH_gamma,M_VH_delta,M_PL_theta,M_PL_gamma,M_PL_delta,...
    F_IL_theta,F_IL_gamma,F_IL_delta,F_DH_theta,F_DH_gamma,F_DH_delta,F_VH_theta,F_VH_gamma,F_VH_delta,F_PL_theta,F_PL_gamma,F_PL_delta,...
    F_IL_D_theta,F_IL_D_gamma,F_IL_D_delta,F_DH_D_theta,F_DH_D_gamma,F_DH_D_delta,F_VH_D_theta,F_VH_D_gamma,F_VH_D_delta,F_PL_D_theta,F_PL_D_gamma,F_PL_D_delta,...
    F_IL_P_theta,F_IL_P_gamma,F_IL_P_delta,F_DH_P_theta,F_DH_P_gamma,F_DH_P_delta,F_VH_P_theta,F_VH_P_gamma,F_VH_P_delta,F_PL_P_theta,F_PL_P_gamma,F_PL_P_delta,...
    F_IL_E_theta,F_IL_E_gamma,F_IL_E_delta,F_DH_E_theta,F_DH_E_gamma,F_DH_E_delta,F_VH_E_theta,F_VH_E_gamma,F_VH_E_delta,F_PL_E_theta,F_PL_E_gamma,F_PL_E_delta,...
    F_IL_M_theta,F_IL_M_gamma,F_IL_M_delta,F_DH_M_theta,F_DH_M_gamma,F_DH_M_delta,F_VH_M_theta,F_VH_M_gamma,F_VH_M_delta,F_PL_M_theta,F_PL_M_gamma,F_PL_M_delta] ...
    = Format4Bootstrap_BandPower2(subjs,f,M_IL_Pxx,M_PL_Pxx,M_DH_Pxx,M_VH_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx)
%% Setup

% Subject ID listing: Separate the sexes. A*=male  E*=female
Msubjs = subjs(contains(subjs,'A')); % males
Fsubjs = subjs(contains(subjs,'E')); % females

%% Index frequency ranges
% Theta (4-12Hz), Gamma (30-80Hz), and Delta(1-4Hz)
    % Theta
    t1 = knnsearch(f,4);
    t2 = knnsearch(f,12);
%     theta = f(t1:t2); %theta band frequencies
    
    % Gamma
    g1 = knnsearch(f,30);
    g2 = knnsearch(f,80);
%     gamma = f(g1:g2); %gamma band frequencies
    
    % Delta 
    d1 = knnsearch(f,1);
    d2 = knnsearch(f,4);
%     delta = f(d1:d2); %delta band frequencies
    
%% Calculate band power: BL arena, 5-15 cm/s velocity - Outputs in dB units!
%% Males

% Preallocate output space
    M_IL_theta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_IL_gamma = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_IL_delta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_DH_theta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_DH_gamma = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_DH_delta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_VH_theta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_VH_gamma = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_VH_delta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_PL_theta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_PL_gamma = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));
    M_PL_delta = cell(length(Msubjs),max(cellfun('prodofsize',M_IL_Pxx))/length(f));

for si = 1:length(Msubjs) %loop male subjects
    for ri = 1:size(M_IL_Pxx{si,1},1) %loop trials
        % mPFC-IL
        M_IL_theta{si,ri} = pow2db(bandpower(M_IL_Pxx{si,1}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
        M_IL_gamma{si,ri} = pow2db(bandpower(M_IL_Pxx{si,1}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
        M_IL_delta{si,ri} = pow2db(bandpower(M_IL_Pxx{si,1}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
        % dHPC
        M_DH_theta{si,ri} = pow2db(bandpower(M_DH_Pxx{si,1}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
        M_DH_gamma{si,ri} = pow2db(bandpower(M_DH_Pxx{si,1}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
        M_DH_delta{si,ri} = pow2db(bandpower(M_DH_Pxx{si,1}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
        % vHPC
        M_VH_theta{si,ri} = pow2db(bandpower(M_VH_Pxx{si,1}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
        M_VH_gamma{si,ri} = pow2db(bandpower(M_VH_Pxx{si,1}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
        M_VH_delta{si,ri} = pow2db(bandpower(M_VH_Pxx{si,1}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
        % mPFC-PL
        M_PL_theta{si,ri} = pow2db(bandpower(M_PL_Pxx{si,1}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
        M_PL_gamma{si,ri} = pow2db(bandpower(M_PL_Pxx{si,1}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
        M_PL_delta{si,ri} = pow2db(bandpower(M_PL_Pxx{si,1}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
    end
end
clear si ri M_IL_Pxx M_PL_Pxx M_DH_Pxx M_VH_Pxx 


%% Females: All stages combined
maxT = 28; %maximum number of trials for any given female subject
% Preallocate space: Hormones concatenated
%     F_IL_theta = cell(length(Fsubjs),sum(max(cellfun('prodofsize',F_IL_Pxx(:,:)))/length(f)));   %this way creates too many extra empty cells at the end
    F_IL_theta = cell(length(Fsubjs),maxT);
    F_IL_gamma = cell(length(Fsubjs),maxT);
    F_IL_delta = cell(length(Fsubjs),maxT);
    F_DH_theta = cell(length(Fsubjs),maxT);
    F_DH_gamma = cell(length(Fsubjs),maxT);
    F_DH_delta = cell(length(Fsubjs),maxT);
    F_VH_theta = cell(length(Fsubjs),maxT);
    F_VH_gamma = cell(length(Fsubjs),maxT);
    F_VH_delta = cell(length(Fsubjs),maxT);
    F_PL_theta = cell(length(Fsubjs),maxT);
    F_PL_gamma = cell(length(Fsubjs),maxT);
    F_PL_delta = cell(length(Fsubjs),maxT);
clear maxT
    
% Get theta, gamma, and delta band power for all trials
for si = 1:length(Fsubjs)
    % Concatenate subject's Pxx data from all hormone states
    il = [F_IL_Pxx{si,1}; F_IL_Pxx{si,2}; F_IL_Pxx{si,3}; F_IL_Pxx{si,4}];
    dh = [F_DH_Pxx{si,1}; F_DH_Pxx{si,2}; F_DH_Pxx{si,3}; F_DH_Pxx{si,4}];
    vh = [F_IL_Pxx{si,1}; F_IL_Pxx{si,2}; F_IL_Pxx{si,3}; F_IL_Pxx{si,4}];
    pl = [F_IL_Pxx{si,1}; F_IL_Pxx{si,2}; F_IL_Pxx{si,3}; F_IL_Pxx{si,4}];
    for ri = 1:size(il,1) %loop trials (all stages)
        % mPFC-IL
        F_IL_theta{si,ri} = pow2db(bandpower(il(ri,:),f,[f(t1) f(t2)],'psd')); %theta
        F_IL_gamma{si,ri} = pow2db(bandpower(il(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
        F_IL_delta{si,ri} = pow2db(bandpower(il(ri,:),f,[f(d1) f(d2)],'psd')); %delta
        % dHPC
        F_DH_theta{si,ri} = pow2db(bandpower(dh(ri,:),f,[f(t1) f(t2)],'psd')); 
        F_DH_gamma{si,ri} = pow2db(bandpower(dh(ri,:),f,[f(g1) f(g2)],'psd'));
        F_DH_delta{si,ri} = pow2db(bandpower(dh(ri,:),f,[f(d1) f(d2)],'psd'));
        % vHPC
        F_VH_theta{si,ri} = pow2db(bandpower(vh(ri,:),f,[f(t1) f(t2)],'psd')); 
        F_VH_gamma{si,ri} = pow2db(bandpower(vh(ri,:),f,[f(g1) f(g2)],'psd'));
        F_VH_delta{si,ri} = pow2db(bandpower(vh(ri,:),f,[f(d1) f(d2)],'psd'));
        % mPFC-PL
        F_PL_theta{si,ri} = pow2db(bandpower(pl(ri,:),f,[f(t1) f(t2)],'psd')); 
        F_PL_gamma{si,ri} = pow2db(bandpower(pl(ri,:),f,[f(g1) f(g2)],'psd')); 
        F_PL_delta{si,ri} = pow2db(bandpower(pl(ri,:),f,[f(d1) f(d2)],'psd'));
    end
    clear ri il dh vh pl
end
clear si

    
%% Females: Hormone stages separated   
% Preallocate space: Diestrus
    F_IL_D_theta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_IL_D_gamma = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_IL_D_delta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_DH_D_theta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_DH_D_gamma = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_DH_D_delta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_VH_D_theta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_VH_D_gamma = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_VH_D_delta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_PL_D_theta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_PL_D_gamma = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
    F_PL_D_delta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,1)))/length(f));
% Preallocate space: Proestrus
    F_IL_P_theta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_IL_P_gamma = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_IL_P_delta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_DH_P_theta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_DH_P_gamma = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_DH_P_delta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_VH_P_theta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_VH_P_gamma = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_VH_P_delta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_PL_P_theta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_PL_P_gamma = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
    F_PL_P_delta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,2)))/length(f));
% Preallocate space: Estrus
    F_IL_E_theta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_IL_E_gamma = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_IL_E_delta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_DH_E_theta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_DH_E_gamma = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_DH_E_delta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_VH_E_theta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_VH_E_gamma = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_VH_E_delta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_PL_E_theta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_PL_E_gamma = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
    F_PL_E_delta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,3)))/length(f));
% Preallocate space: Metestrus
    F_IL_M_theta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_IL_M_gamma = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_IL_M_delta = cell(length(F_IL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_DH_M_theta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_DH_M_gamma = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_DH_M_delta = cell(length(F_DH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_VH_M_theta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_VH_M_gamma = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_VH_M_delta = cell(length(F_VH_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_PL_M_theta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_PL_M_gamma = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    F_PL_M_delta = cell(length(F_PL_Pxx),max(cellfun('prodofsize',F_IL_Pxx(:,4)))/length(f));
    
    
for si = 1:length(Fsubjs) %loop thru subjects
    for ti = 1:4 %loop thru hormone states: column 1=Diestrus, 2=Proestrus, 3=Estrus, 4=Metestrus
        for ri = 1:size(F_IL_Pxx{si,ti},1) %loop trials
            switch ti
                case 1 %Diestrus
                    F_IL_D_theta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_IL_D_gamma{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_IL_D_delta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_DH_D_theta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_DH_D_gamma{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_DH_D_delta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_VH_D_theta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_VH_D_gamma{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_VH_D_delta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_PL_D_theta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_PL_D_gamma{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_PL_D_delta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                case 2 %Proestrus
                    F_IL_P_theta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_IL_P_gamma{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_IL_P_delta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_DH_P_theta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_DH_P_gamma{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_DH_P_delta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_VH_P_theta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_VH_P_gamma{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_VH_P_delta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_PL_P_theta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_PL_P_gamma{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_PL_P_delta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                case 3 %Estrus
                    F_IL_E_theta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_IL_E_gamma{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_IL_E_delta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_DH_E_theta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_DH_E_gamma{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_DH_E_delta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_VH_E_theta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_VH_E_gamma{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_VH_E_delta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_PL_E_theta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_PL_E_gamma{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_PL_E_delta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                case 4 %Metestrus
                    F_IL_M_theta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); %theta
                    F_IL_M_gamma{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); %gamma
                    F_IL_M_delta{si,ri} = pow2db(bandpower(F_IL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); %delta
                    F_DH_M_theta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); 
                    F_DH_M_gamma{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); 
                    F_DH_M_delta{si,ri} = pow2db(bandpower(F_DH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); 
                    F_VH_M_theta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd')); 
                    F_VH_M_gamma{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd'));
                    F_VH_M_delta{si,ri} = pow2db(bandpower(F_VH_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); 
                    F_PL_M_theta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(t1) f(t2)],'psd'));
                    F_PL_M_gamma{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(g1) f(g2)],'psd')); 
                    F_PL_M_delta{si,ri} = pow2db(bandpower(F_PL_Pxx{si,ti}(ri,:),f,[f(d1) f(d2)],'psd')); 
            end %switch
        end %trials
    end %hormones
    clear ti
end %subjects
clear si F_IL_Pxx F_PL_Pxx F_DH_Pxx F_VH_Pxx

end %function

