%PowSpec5to15Trials
% [f,M_IL_Pxx,M_DH_Pxx,M_VH_Pxx,M_PL_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15Trials(subjs,M_IL,M_DH,M_VH,M_PL,F_IL,F_DH,F_VH,F_PL)
% 
% Generates power spectra for each trial for each subject, using data from
% all familiar (BL) arena recordings, epochs of locomotor movement between
% 5-15 cm/s. Female data is indexed in the 2nd dimension by hormone state.
% 
% Calculates power spectra using the welch method (pwelch).
% 
%   Called by:
%       - Thesis6_Format4Bootstrap_5to15.m
% 
%   Calls data generated by:
%       Format4Bootstrap_LFP.m:  'LFP-BL-5to15_boot.mat'
% 
% KJS init: 2020-02-20

function [f,M_IL_Pxx,M_DH_Pxx,M_VH_Pxx,M_PL_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15Trials(subjs,M_IL,M_DH,M_VH,M_PL,F_IL,F_DH,F_VH,F_PL)
% Setup

% pwelch parameters
Fs = 2000; %sampling frequency (Hz)
window = Fs*0.4; 
noverlap = window *0.9;
nfft = 2*Fs;

% Subject IDs - separate the sexes
Msubjs = subjs(contains(subjs,'A')); % males
Fsubjs = subjs(contains(subjs,'E')); % females

%% Males

% Preallocate output space
M_IL_Pxx = cell(size(M_IL));
M_DH_Pxx = cell(size(M_DH));
M_VH_Pxx = cell(size(M_VH));
M_PL_Pxx = cell(size(M_PL));

% Calculate pwelch: Single curve per brain region, per trial. (Trials nested within subject cells)
for si = 1:length(Msubjs) %loop thru male subjects
    tic;
    fprintf('Calculating PowSpec for %s..\n',Msubjs{si})
    for ri = 1:length(M_IL{si,1}) %loop trials
        disp('.')
        [M_IL_Pxx{si,1}(ri,:),f] = pwelch(M_IL{si,1}{ri},window,noverlap,nfft,Fs); % f = frequency vector
        [M_DH_Pxx{si,1}(ri,:)] = pwelch(M_DH{si,1}{ri},window,noverlap,nfft,Fs);
        [M_VH_Pxx{si,1}(ri,:)] = pwelch(M_VH{si,1}{ri},window,noverlap,nfft,Fs);
        [M_PL_Pxx{si,1}(ri,:)] = pwelch(M_PL{si,1}{ri},window,noverlap,nfft,Fs);
    end
    toc
    clear ri
end
clear si M_IL M_PL M_DH M_VH

% Constrain data in the frequency domain: 0.5-100 Hz
x1 = knnsearch(f,0.5);
x2 = knnsearch(f,100);
f = f(x1:x2); %frequency vector
for si = 1:length(Msubjs)
    [M_IL_Pxx{si,1}] = M_IL_Pxx{si,1}(:,x1:x2);
    [M_DH_Pxx{si,1}] = M_DH_Pxx{si,1}(:,x1:x2);
    [M_VH_Pxx{si,1}] = M_VH_Pxx{si,1}(:,x1:x2);
    [M_PL_Pxx{si,1}] = M_PL_Pxx{si,1}(:,x1:x2);
end
clear si

%% Females

% Preallocate output space: all hormone states together
F_IL_Pxx = cell(size(F_IL));
F_DH_Pxx = cell(size(F_DH));
F_VH_Pxx = cell(size(F_VH));
F_PL_Pxx = cell(size(F_PL));

% Calculate pwelch: Single curve per brain region, per subject. (all trials concatenated)
for si = 1:length(Fsubjs) %loop thru female subjects
    tic;
    fprintf('Calculating PowSpec for %s..\n',Fsubjs{si})
    for ci = 1:4 %loop hormone states
        for ri = 1:length(F_IL{si,ci}) %loop trials
            disp('.')
            [F_IL_Pxx{si,ci}(ri,:)] = pwelch(F_IL{si,ci}{ri},window,noverlap,nfft,Fs); % f = frequency vector
            [F_DH_Pxx{si,ci}(ri,:)] = pwelch(F_DH{si,ci}{ri},window,noverlap,nfft,Fs);
            [F_VH_Pxx{si,ci}(ri,:)] = pwelch(F_VH{si,ci}{ri},window,noverlap,nfft,Fs);
            [F_PL_Pxx{si,ci}(ri,:)] = pwelch(F_PL{si,ci}{ri},window,noverlap,nfft,Fs);
        end %trials in one cell
        clear ri
    end %hormones
    clear ci
    toc
end
clear si F_IL F_PL F_DH F_VH

% Constrain data in the frequency domain: 0.5-100 Hz
for si = 1:length(Fsubjs)
    for ci = 1:4 %loop hormone states
        [F_IL_Pxx{si,ci}] = F_IL_Pxx{si,ci}(:,x1:x2);
        [F_DH_Pxx{si,ci}] = F_DH_Pxx{si,ci}(:,x1:x2);
        [F_VH_Pxx{si,ci}] = F_VH_Pxx{si,ci}(:,x1:x2);
        [F_PL_Pxx{si,ci}] = F_PL_Pxx{si,ci}(:,x1:x2);
    end
    clear ci
end
clear si x*

end %function
