%% PowSpec5to15_Hormones
% [F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15_Hormones(Fsubjs,F_IL,F_DH,F_VH,F_PL)
% 
% Generates power spectra for female subjects, using concatenated data from
% all familiar (BL) arena recordings, epochs of locomotor movement between
% 5-15 cm/s. 
% Female data is separated by hormone state, within-subject.
% 
%   2nd dimension of each cell array indexes estrous stage:
%     F_*{:,1}=Diestrus (D)
%     F_*{:,2}=Proestrus (P)
%     F_*{:,3}=Estrus (E)
%     F_*{:,4}=Metestrus (M)  **Included for MvF comparisons, Ignored for female hormone comparisons**
% 
% Calculates power spectra using the welch method (pwelch).
% 
%   Called by:
%       - Thesis6_Format4Bootstrap_5to15.m
% 
%   Calls data generated by:
%       Format4Bootstrap_LFP.m:  'LFP-BL-5to15_boot.mat'
% 
% KJS init: 2020-02-19

function [F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15_Hormones(Fsubjs,F_IL,F_DH,F_VH,F_PL)

%% Setup

% pwelch parameters
Fs = 2000; %sampling frequency (Hz)
window = Fs*0.4; 
noverlap = window *0.9;
nfft = 2*Fs;

% Preallocate output space: 4 hormone states
F_IL_Pxx = cell(length(Fsubjs),4);
F_DH_Pxx = cell(length(Fsubjs),4);
F_VH_Pxx = cell(length(Fsubjs),4);
F_PL_Pxx = cell(length(Fsubjs),4);
            
%% Females
% Calculate pwelch: 4 curves per brain region, per subject. (1 curve per hormone state)

for si = 1:length(Fsubjs) %loop thru female subjects
    fprintf('Calculating PowSpec x Hormones for %s...\n',Fsubjs{si})
    tic;
    for hi = 1:4 %loop hormone states
        disp('.')
%         [F_IL_Pxx{si,hi},F] = pwelch(horzcat(F_IL{si,hi}{:}),window,noverlap,nfft,Fs); % f = frequency vector
%         [F_DH_Pxx{si,hi}] = pwelch(horzcat(F_DH{si,hi}{:}),window,noverlap,nfft,Fs);
%         [F_VH_Pxx{si,hi}] = pwelch(horzcat(F_VH{si,hi}{:}),window,noverlap,nfft,Fs);
%         [F_PL_Pxx{si,hi}] = pwelch(horzcat(F_PL{si,hi}{:}),window,noverlap,nfft,Fs);
        [F_IL_Pxx{si,hi},F] = pwelch(cat(1,F_IL{si,hi}{:}),window,noverlap,nfft,Fs); % f = frequency vector
        [F_DH_Pxx{si,hi}] = pwelch(cat(1,F_DH{si,hi}{:}),window,noverlap,nfft,Fs);
        [F_VH_Pxx{si,hi}] = pwelch(cat(1,F_VH{si,hi}{:}),window,noverlap,nfft,Fs);
        [F_PL_Pxx{si,hi}] = pwelch(cat(1,F_PL{si,hi}{:}),window,noverlap,nfft,Fs);
    end
    toc
end
clear si hi F_IL F_PL F_DH F_VH

% Constrain data in the frequency domain: 0.5-100 Hz                        % *** CHECK THIS FIRST ***
x1 = knnsearch(F,0.5);
x2 = knnsearch(F,100);
for si = 1:length(Fsubjs)
    for hi = 1:4 %loop thru hormone states (columns in cell array)
        [F_IL_Pxx{si,hi}] = F_IL_Pxx{si,hi}(x1:x2);
        [F_DH_Pxx{si,hi}] = F_DH_Pxx{si,hi}(x1:x2);
        [F_VH_Pxx{si,hi}] = F_VH_Pxx{si,hi}(x1:x2);
        [F_PL_Pxx{si,hi}] = F_PL_Pxx{si,hi}(x1:x2);
    end
end
clear si hi F x*

end %function
