%PowSpec5to15
% [f,M_IL_Pxx,M_DH_Pxx,M_VH_Pxx,M_PL_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15(subjs,M_IL,M_DH,M_VH,M_PL,F_IL,F_DH,F_VH,F_PL)
% 
% Generates power spectra for each subject, using concatenated data from
% all familiar (BL) arena recordings, epochs of locomotor movement between
% 5-15 cm/s. Female data combines all hormone states.
% 
% Calculates power spectra using the welch method (pwelch).
% 
%   Called by:
%       - Thesis6_Format4Bootstrap_5to15.m
% 
%   Calls data generated by:
%       Format4Bootstrap_LFP.m:  'LFP-BL-5to15_boot.mat'
% 
% KJS init: 2020-02-18
% KJS edit: 2020-02-19

function [f,M_IL_Pxx,M_DH_Pxx,M_VH_Pxx,M_PL_Pxx,F_IL_Pxx,F_DH_Pxx,F_VH_Pxx,F_PL_Pxx] = PowSpec5to15(subjs,M_IL,M_DH,M_VH,M_PL,F_IL,F_DH,F_VH,F_PL)
% Setup

% pwelch parameters
Fs = 2000; %sampling frequency (Hz)
window = Fs*0.4; 
noverlap = window *0.9;
nfft = 2*Fs;

% Subject IDs - separate the sexes
Msubjs = subjs(contains(subjs,'A')); % males
Fsubjs = subjs(contains(subjs,'E')); % females

%% Males

% Preallocate output space
M_IL_Pxx = cell(size(M_IL));
M_DH_Pxx = cell(size(M_DH));
M_VH_Pxx = cell(size(M_VH));
M_PL_Pxx = cell(size(M_PL));

% Calculate pwelch: Single curve per brain region, per subject. (all trials concatenated)
for si = 1:length(Msubjs) %loop thru male subjects
    tic;
    fprintf('Calculating PowSpec for %s..\n',Msubjs{si})
%     [M_IL_Pxx{si,1},f] = pwelch(horzcat(M_IL{si,1}{:}),window,noverlap,nfft,Fs); % f = frequency vector
%     [M_DH_Pxx{si,1}] = pwelch(horzcat(M_DH{si,1}{:}),window,noverlap,nfft,Fs);
%     [M_VH_Pxx{si,1}] = pwelch(horzcat(M_VH{si,1}{:}),window,noverlap,nfft,Fs);
%     [M_PL_Pxx{si,1}] = pwelch(horzcat(M_PL{si,1}{:}),window,noverlap,nfft,Fs);
    [M_IL_Pxx{si,1},f] = pwelch(cat(1,M_IL{si,1}{:}),window,noverlap,nfft,Fs); % f = frequency vector
    [M_DH_Pxx{si,1}] = pwelch(cat(1,M_DH{si,1}{:}),window,noverlap,nfft,Fs);
    [M_VH_Pxx{si,1}] = pwelch(cat(1,M_VH{si,1}{:}),window,noverlap,nfft,Fs);
    [M_PL_Pxx{si,1}] = pwelch(cat(1,M_PL{si,1}{:}),window,noverlap,nfft,Fs);
    toc
end
clear si M_IL M_PL M_DH M_VH

% Constrain data in the frequency domain: 0.5-100 Hz
x1 = knnsearch(f,0.5);
x2 = knnsearch(f,100);
f = f(x1:x2); %frequency vector
for si = 1:length(Msubjs)
    [M_IL_Pxx{si,1}] = M_IL_Pxx{si,1}(x1:x2);
    [M_DH_Pxx{si,1}] = M_DH_Pxx{si,1}(x1:x2);
    [M_VH_Pxx{si,1}] = M_VH_Pxx{si,1}(x1:x2);
    [M_PL_Pxx{si,1}] = M_PL_Pxx{si,1}(x1:x2);
end
clear si

            
%% Females

% Preallocate output space: all hormone states together
F_IL_Pxx = cell(length(Fsubjs),1);
F_DH_Pxx = cell(length(Fsubjs),1);
F_VH_Pxx = cell(length(Fsubjs),1);
F_PL_Pxx = cell(length(Fsubjs),1);

% For each female subject, concatenate all hormone states
for si = 1:length(Fsubjs)
    F_IL{si,1} = [F_IL{si,1}; F_IL{si,2}; F_IL{si,3}; F_IL{si,4}];
    F_DH{si,1} = [F_DH{si,1}; F_DH{si,2}; F_DH{si,3}; F_DH{si,4}];
    F_VH{si,1} = [F_VH{si,1}; F_VH{si,2}; F_VH{si,3}; F_VH{si,4}];
    F_PL{si,1} = [F_PL{si,1}; F_PL{si,2}; F_PL{si,3}; F_PL{si,4}];
end
F_IL(:,2:4)=[];
F_DH(:,2:4)=[];
F_VH(:,2:4)=[];
F_PL(:,2:4)=[];
clear si

% Calculate pwelch: Single curve per brain region, per subject. (all trials concatenated)
for si = 1:length(Fsubjs) %loop thru female subjects
    tic;
    fprintf('Calculating PowSpec for %s..\n',Fsubjs{si})
%     [F_IL_Pxx{si,1}] = pwelch(horzcat(F_IL{si,1}{:}),window,noverlap,nfft,Fs); % f = frequency vector
%     [F_DH_Pxx{si,1}] = pwelch(horzcat(F_DH{si,1}{:}),window,noverlap,nfft,Fs);
%     [F_VH_Pxx{si,1}] = pwelch(horzcat(F_VH{si,1}{:}),window,noverlap,nfft,Fs);
%     [F_PL_Pxx{si,1}] = pwelch(horzcat(F_PL{si,1}{:}),window,noverlap,nfft,Fs);
    [F_IL_Pxx{si,1}] = pwelch(cat(1,F_IL{si,1}{:}),window,noverlap,nfft,Fs); % f = frequency vector
    [F_DH_Pxx{si,1}] = pwelch(cat(1,F_DH{si,1}{:}),window,noverlap,nfft,Fs);
    [F_VH_Pxx{si,1}] = pwelch(cat(1,F_VH{si,1}{:}),window,noverlap,nfft,Fs);
    [F_PL_Pxx{si,1}] = pwelch(cat(1,F_PL{si,1}{:}),window,noverlap,nfft,Fs);
    toc 
end
clear si F_IL F_PL F_DH F_VH

% Constrain data in the frequency domain: 0.5-100 Hz
for si = 1:length(Fsubjs)
    [F_IL_Pxx{si,1}] = F_IL_Pxx{si,1}(x1:x2);
    [F_DH_Pxx{si,1}] = F_DH_Pxx{si,1}(x1:x2);
    [F_VH_Pxx{si,1}] = F_VH_Pxx{si,1}(x1:x2);
    [F_PL_Pxx{si,1}] = F_PL_Pxx{si,1}(x1:x2);
end
clear si x*

end %function
